### ISSUE TITLE
dA.py is missing

### ISSUE THREAD

**Issue by sumo8291** [boyangumn/DCN#1]
Hi

I was going through your paper and decided to run your code. But I am getting this error. I guess u haven't provided the dA.py file. I have copied the commented code from dA_init.py to remedy nthe
![da py](https://user-images.githubusercontent.com/8149573/29653534-871caa8e-88ed-11e7-833b-a6003f4164c5.png)

Thanks
Soumava Kumar Roy

**Comment by ductri** [comment]
Is there any update on this issue?
