### ISSUE TITLE
Lower NMI, ARI, ACC than expected running raw_mnist experiment

### ISSUE THREAD

**Issue by hereismari** [boyangumn/DCN#4]
I've executed the run_raw_mnist.py with 'hidden_dim': [500, 500, 2000, 10] like described in the paper.
```
THEANO_FLAGS='floatX=float32' python run_raw_mnist.py
```
But I got lower NMI, ARI, ACC than expected:

```
NMI for deep clustering: 0.48
ARI for deep clustering: 0.35
ACC for deep clustering: 0.52
```

Is this the expected result? The results in the paper are, respectively, around: 0.81, 0.75 and 0.83

**Comment by boyangumn** [comment]
Hi,

Thanks for your interest, and sorry the code listed here is actually outdated --- it corresponds to an earlier submission of the paper. 

I spent some time in order to make the code run out of the box. Please see the new version here
https://github.com/boyangumn/DCN-New

**Comment by hereismari** [comment]
Thanks for the reply, I'll definitely check it out!
